// Generated by gencpp from file casper/Encoder.msg
// DO NOT EDIT!


#ifndef CASPER_MESSAGE_ENCODER_H
#define CASPER_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace casper
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : header()
    , Current(0.0)
    , Encoder1(0.0)
    , Encoder2(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Current(0.0)
    , Encoder1(0.0)
    , Encoder2(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _Current_type;
  _Current_type Current;

   typedef double _Encoder1_type;
  _Encoder1_type Encoder1;

   typedef double _Encoder2_type;
  _Encoder2_type Encoder2;





  typedef boost::shared_ptr< ::casper::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::casper::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::casper::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::casper::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::casper::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::casper::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::casper::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::casper::Encoder_<ContainerAllocator1> & lhs, const ::casper::Encoder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Current == rhs.Current &&
    lhs.Encoder1 == rhs.Encoder1 &&
    lhs.Encoder2 == rhs.Encoder2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::casper::Encoder_<ContainerAllocator1> & lhs, const ::casper::Encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace casper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::casper::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::casper::Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casper::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casper::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casper::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casper::Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::casper::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9684e83a0d0addb6c2e31639cbbdce64";
  }

  static const char* value(const ::casper::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9684e83a0d0addb6ULL;
  static const uint64_t static_value2 = 0xc2e31639cbbdce64ULL;
};

template<class ContainerAllocator>
struct DataType< ::casper::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "casper/Encoder";
  }

  static const char* value(const ::casper::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::casper::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 Current\n"
"float64 Encoder1\n"
"float64 Encoder2\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::casper::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::casper::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Current);
      stream.next(m.Encoder1);
      stream.next(m.Encoder2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::casper::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::casper::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Current: ";
    Printer<double>::stream(s, indent + "  ", v.Current);
    s << indent << "Encoder1: ";
    Printer<double>::stream(s, indent + "  ", v.Encoder1);
    s << indent << "Encoder2: ";
    Printer<double>::stream(s, indent + "  ", v.Encoder2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASPER_MESSAGE_ENCODER_H
